name: "conv-vae-128"
# information about the training task
output_size: 6

# information about the regressor
encoding_size: 128 # should be the same as the encoding
regressor_hidden_size_1: 64
regressor_hidden_size_2: 64
loss: "MSE"

# The number of epochs the MLP is supposed to be trained
# epochs: 1000
batch_size: 32

# information about the sp specified by the exp/run
sensor_processing: 'ConvVaeSensorProcessing'
sp_experiment: 'sensorprocessing_conv_vae'
sp_run: 'proprio_128'

# proprioception_training_task: 'proprio_regressor_training'
# proprioception_testing_task: 'proprio_regressor_validation'

# the training data: use the default

# the training data in the demonstration / subrun / camera form 
#training_data:
#  - ["freeform", "2024_12_26__16_40_20", "dev2"]
#  - ["freeform", "2024_12_26__16_44_06", "dev2"]


# the validation data in the demonstration / subrun form 
#validation_data:
#  - ["freeform", "2024_12_26__16_40_20", "dev2"]
#  - ["freeform", "2024_12_26__16_44_06", "dev2"]

