"""
abstract_rcco.py

Contains AbstractRCComponent, the root class for the robot controller components
"""

from abc import ABC


_MISSING = object()


class AbstractRCComponent(ABC):
    """The root class for robot controller components (rcco-*). A typical model is a neural network, but can be other things that visualize, log, memorize, visualize, perform safety checks etc.

    An RC component is described

    The main aspects of the model are:
    - **name** 
    - **architecture** the code that implements the component, or the structure of the neural network. This is normally created in the init or implemented as functions in inherited functions
    - **state** the data created through training. Can be loaded and saved. Example, weights of neural networks etc. 
    - **context** data accumulated during running, eg. LSTM state, transformer context. Can be loaded and saved. Normally the context is accumulated through the input
    - **input** the current input, which can be set without running the update. It might be saved with the context. 
        FIXME: it needs multiple named inputs
    - **output** the current output, generated by running the update. It has a marker whether it is up to date, i.e. if it had been generated from the current input. 
        FIXME: it needs multiple named outputs
    - **dirty** this bit verifies that the output(s) had been recalculated from the current inputs
    """
    def __init__(self, exp_rcco):
        self.inputs = {}
        self.outputs = {}
        self.input_sizes = {}
        self.output_sizes = {}
        self.dirty = False
        self.exp = exp_rcco

    def set_input(self, name, value=_MISSING):
        """Set a named input and mark this component for propagation.

        The one-argument form remains available for components with exactly one
        input port.
        """
        if value is _MISSING:
            value = name
            if len(self.inputs) != 1:
                raise ValueError(
                    "The input name is required when a component does not have "
                    "exactly one input port"
                )
            name = next(iter(self.inputs))
        if name not in self.inputs:
            raise KeyError(f"Unknown input port {name!r}")
        if value is None:
            raise ValueError(f"Input {name!r} cannot be None")
        self.inputs[name] = value
        self.dirty = True

    def inputs_ready(self):
        """Return whether every declared input currently contains a value."""
        return all(value is not None for value in self.inputs.values())

    def propagate(self):
        """Propagate the input to the output, update the context, set the dirty flag"""
        self.dirty = False

    def save(self):
        """Save the state, context, input and output, to different files"""
        pass

    def load(self):
        """Load the state, context, input and output from different files"""
        pass

    def reset_context(self):
        """Clear runtime values without changing trained model state."""
        for name in self.inputs:
            self.inputs[name] = None
        for name in self.outputs:
            self.outputs[name] = None
        self.dirty = False
