# resnet-50 00 
name : 'resnet-50-128'

image_size: [64, 64]
latent_size: 128


reductor_step_1: 512
proprio_step_1: 64
proprio_step_2: 16
output_size: 6

model: 'ResNetProprioTunedRegression'
loss: 'MSELoss' # alternatively it could be L1Loss
epochs: 40
learning_rate: 0.001
batch_size: 32
# batch_size: 1

freeze_feature_extractor: True

# the training data in the demonstration / subrun form 
training_data:
  - ["freeform", "2024_12_26__16_40_20"]
  - ["freeform", "2024_12_26__16_44_06"]
