name : 'vgg19-128'

image_size: [64, 64]
latent_size: 128

model: 'VGG19ProprioTunedRegression'
loss: 'MSELoss' # alternatively it could be L1Loss
epochs: 10
learning_rate: 0.001
batch_size: 32
output_size: 6

freeze_feature_extractor: True

# the training data in the demonstration / subrun form 
training_data:
  - ["freeform", "2024_12_26__16_40_20", "dev2"]
  - ["freeform", "2024_12_26__16_44_06", "dev2"]

