name : 'vgg19-128'
latent_size: 128
model: 'VGG19ProprioTunedRegression'
loss: 'MSELoss' # alternatively it could be L1Loss
epochs: 10
learning_rate: 0.001
batch_size: 32
output_size: 6

freeze_feature_extractor: True

# proprioception_training_task: 'proprio_sp_training'
# proprioception_testing_task: 'proprio_sp_validation'

# the training data is the experiment/run/subrun
training_data:
  -["freeform", "2024_12_26__16_40_20"]
  -["freeform", "2024_12_26__16_44_06"]

# the testing data is the experiment/run/subrun
testing_data:
  -["freeform", "testing"]

